### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by sunesimonsen** [thgh/rollup-plugin-url-import#1]
It is not unusual to have import urls looking like this `https://unpkg.com/lit-html@^1.0.0/lit-html.js` where the version is a range. This will result in a redirection from unpkg.

I would suggest following the redirects (maybe with a limit 😄). I did a quick spike on it, nothing serious, but it seems to work for my case.

Instead of just failing here: https://github.com/thgh/rollup-plugin-url-import/blob/master/src/index.js#L44

You could do something like this:

```js
        const location = response.headers && response.headers.location
        if (location) {
          const redirection = location.startsWith('http')
            ? location
            : require('url').resolve(url, location)

          return fetchText(redirection).then(resolve, reject);
        } else {
          reject(new Error('Error statusCode ' + response.statusCode));
        }
```

**Comment by thgh** [comment]
Very interested in PR!

**Comment by sunesimonsen** [comment]
Okay let me do that. It will probably take a day or two before I have time. But I'll get back to you.
